resolver: lts-10.5

packages:
- .

extra-deps:
- permutation-0.5.0.5

allow-newer: true

# Override default flag values for local packages and extra-deps
# flags: {}

extra-include-dirs:
- C:\Users\sdl96354\AppData\Local\Programs\HaskellPlatform\8.2.1\msys\mingw64\include
extra-lib-dirs:
- C:\Users\sdl96354\AppData\Local\Programs\HaskellPlatform\8.2.1\msys\mingw64\lib
